GET http://localhost:5015/games

###
GET http://localhost:5015/games/1

###
POST http://localhost:5015/games
Content-Type: application/json

{
    "Name":"Super Mario Bros . WOnder",
    "Genre":"Platformer",
    "Price":59.55,
    "ReleaseDate":"2023-10-20"
}