GET http://localhost:5015/games

###
GET http://localhost:5015/games/1

###
POST http://localhost:5015/games
Content-Type: application/json

{
    "Name":"Car Game",
    "Genre":"Platform",
    "Price":59.55,
    "ReleaseDate":"2023-10-20"
}
# Update
###
PUT http://localhost:5015/games/1
Content-Type: application/json

{
    "name": "Chess",
    "genre": "Iq",
    "price": 11.44,
    "releaseDate": "1902-08-15"
}

###
DELETE http://localhost:5015/games/3





